version: '3'
services:
  apiserver:
    image: shopapi
    container_name: apiserver
    depends_on:
      - shopdb
    command: bash -c "
      chmod +x app/start_api_server.sh && 
      ./app/start_api_server.sh"
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    # automatically restart the image after a change in the code
    # develop:
    #   watch:
    #     - action: sync+restart
    #       path: containerized_app/
    #       target: /app/
  shopdb:
    image: mysql:9
    container_name: db
    environment:
      MYSQL_DATABASE: "api_training"
      MYSQL_ROOT_PASSWORD: "WavestoneApiTraining"
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

networks:
  mynetwork: