---
# Premier play sur la db
- name: MySQL installation and configuration
  hosts: dbserver
  become: true

  # Le role suivant installe et configue MySQL
  roles:
    - role: geerlingguy.mysql
      become: true

  vars_files:
    - geerlingguy.mysql/defaults/main.yml

  tasks:
    - name: Mettre à jour la liste des paquets apt
      apt:
        update_cache: yes

    - name: S'assurer que MySQL est démarré et activé au démarrage
      service:
        name: mysql
        state: started
        enabled: true

    - name: Copier le script de configuration de la DB
      copy:
        src: ../mysql-init/init.sql
        dest: /init.sql
        # Rendre le script exécutable
        mode: "u+x,g=r,o=r"

    - name: Exécuter le script SQL pour initialiser la DB
      ansible.builtin.shell: |
        mysql -u root -p{{ mysql_root_password }} < /init.sql


# Deuxième play sur le serveur API
- name: API server configuration
  hosts: apiserver
  become: true

  tasks:
    - name: Mettre à jour la liste des paquets apt
      apt:
        update_cache: yes

    - name: Copier les fichiers sources dans app
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/anthirion/app/
        mode: u=rw,g=r,o=r
      with_fileglob:
        - "../final_app/*.py"

    - name: Copier les autres fichiers de configuration dans app
      ansible.builtin.copy:
          src:  "{{ item }}"
          dest: /home/anthirion/app/
          mode: u=rw,g=r,o=r
      with_items:
        - "../final_app/.env"
        - "../requirements.txt"
        - "./create_venv.sh"

    - name: Installer Python 3
      apt:
        name: python3
        state: present
        update_cache: true
      become: true

    - name: Installer le module venv de python
      apt:
          name: python3-venv
          state: present
          update_cache: true
      become: true

    - name: Installer pip
      apt:
        name: python3-pip
        state: present
        update_cache: true
      become: true

    - name: Créer et activer un environnement virtuel
      ansible.builtin.shell: |
        chmod +x /home/anthirion/app/create_venv.sh && /home/anthirion/app/create_venv.sh
      
    - name: Installer les dépendances avec les privilèges root
      ansible.builtin.pip:
        requirements: /home/anthirion/app/requirements.txt
        virtualenv: /home/anthirion/app/fastapi_venv

    # - name: Lancer le serveur
    #   ansible.builtin.shell: |
    #     fastapi run /home/anthirion/app/main.py
    #   become: true