---
- name: MySQL configuration
  hosts: dbserver
  become: true

  # le role suivant permet d'installer et de configuer MySQL
  roles:
    - role: geerlingguy.mysql
      become: true
  
  vars_files:
    - geerlingguy.mysql/defaults/main.yml

  tasks:
    - name: Mettre à jour la liste des paquets apt
      apt:
        update_cache: yes

    - name: S'assurer que MySQL est démarré et activé au démarrage
      service:
        name: mysql
        state: started
        enabled: true

    - name: Copier le script de configuration de la DB
      copy:
        src: ../mysql-init/init.sql
        dest: /init.sql
        # Rendre le script exécutable
        mode: "u+x,g=r,o=r"

    - name: Exécuter le script SQL pour initialiser la DB
      ansible.builtin.shell: |
        mysql -u root -p{{ mysql_root_password }} < /init.sql
