---
# Play sur la db
- name: MySQL installation and configuration
  hosts: dbserver
  become: true
  # Les tags permettent de cibler un play ou une tâche dans le playbook
  # on peut exécuter les tâches ou le play taggé uniquement avec l'option --tags de ansible-playbook
  tags: mysql_config

  # Le role suivant installe et configure MySQL
  roles:
    - role: geerlingguy.mysql
      become: true

  vars_files:
    - geerlingguy.mysql/defaults/main.yml

  tasks:
    - name: Mettre à jour la liste des paquets apt
      ansible.builtin.apt:
        update_cache: true

    - name: Autoriser les connexions MySQL depuis n'importe quelle machine
      ansible.builtin.lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address\s*='
        line: 'bind-address = 0.0.0.0'
      notify: Restart MySQL

    - name: Copier le script de configuration de la DB
      ansible.builtin.copy:
        src: ../mysql-init/init.sql
        dest: /init.sql
        # Rendre le script exécutable
        mode: "u+x,g=r,o=r"


    - name: Exécuter le script SQL pour initialiser la DB
      ansible.builtin.shell: |
        mysql -u {{ mysql_user_name }} -p{{ mysql_user_password }} < /init.sql
    
  handlers:
  - name: Restart MySQL
    ansible.builtin.service:
      name: mysql
      state: restarted



# Play sur le serveur API
- name: API server configuration
  hosts: apiserver
  become: true
  tags: api_server_config

  tasks:
    - name: Installer tous les utilitaires nécessaires
      ansible.builtin.apt:
        name: ["python3", "python3-venv", "python3-pip"]
        state: present
        update_cache: true

    - name: Copier les fichiers sources dans app
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/anthirion/app/
        mode: u=rw,g=r,o=r
      with_fileglob:
        - "../final_app/*.py"
      tags: code_updated

    - name: Copier les autres fichiers de configuration dans app
      ansible.builtin.copy:
          src:  "{{ item }}"
          dest: /home/anthirion/app/
          mode: u=rw,g=r,o=r
      with_items:
        - "../final_app/.env"
        - "../requirements.txt"
        - "./create_venv.sh"
      tags: code_updated

    - name: Mettre à jour l'adresse IP du serveur DB dans le .env
      ansible.builtin.lineinfile:
        path: /home/anthirion/app/.env
        regexp: '^HOST='
        line: "HOST = {{ hostvars['db-server']['ansible_host'] }}"

    - name: Créer et activer un environnement virtuel
      ansible.builtin.shell: |
        chmod +x /home/anthirion/app/create_venv.sh && /home/anthirion/app/create_venv.sh
      tags: code_updated

    - name: Installation de packages pour résoudre l'erreur de dépendance à l'installation de mysql-client
      ansible.builtin.apt:
        name: ['pkg-config', 'python3-dev', 'default-libmysqlclient-dev', 'build-essential']
    
    - name: Installer les dépendances de l'app
      ansible.builtin.pip:
        requirements: /home/anthirion/app/requirements.txt
        virtualenv: /home/anthirion/app/fastapi_venv

# impossible de démarrer le serveur automatiquement, le faire à la main avec les étapes suivantes :
# 1. Se connecter au serveur api-server en ssh
# 2. cd app
# 3. source fastapi_venv/bin/activate
# 4. fastapi run main.py

# Play sur la gateway
- name: Gateway configuration
  hosts: gatewayserver
  become: true
  tags: gateway_config
  vars:
    image_name: "custom_krakend"
    container_name: "api_gateway"

  tasks:
    - name: Copier le contenu du répertoire krakend sur le serveur distant
      ansible.builtin.copy:
        src: ./krakend
        dest: /home/anthirion
        mode: u=rw,g=r,o=rx

    - name: >
        Construire l'image Docker de la gateway à partir du Dockerfile uniquement
        si l'image n'est pas déjà construite et si l'argument rebuild est faux.
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: latest
        source: build
        build:
          path: krakend/
        state: present

    - name: Démarrer un conteneur Docker à partir de l'image construite
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}:latest"
        state: started
        ports:
          - "80:8080"                          

    
    # - name: >
    #     Démarrer un conteneur Docker à partir de l'image construite
    #     uniquement si le conteneur n'a pas déjà été lancé
    #   ansible.builtin.shell: |
    #     "docker run -it -p 80:8080 -v $PWD:/krakend/ devopsfaith/krakend"

